### ISSUE TITLE
english version

### ISSUE THREAD

**Issue by JBlond** [sillydong/MySQL_DB_Diff#1]
it would be nice to have an englisch version of this nice tool

**Comment by sillydong** [comment]
OK, I will make an english version soone

**Comment by JBlond** [comment]
I'm still waiting

**Comment by sillydong** [comment]
Sorry man, but I have created a Go version for making diff for mysql databases [https://github.com/sillydong/dbdiffer](https://github.com/sillydong/dbdiffer), would you like to check this out? . For the PHP version, I will update it in few days. This time I will make sure it happens.

**Comment by sillydong** [comment]
@JBlond Hey man, I translated the words in the code and you can see it in English now. 
However, I strongly recommend you move to https://github.com/sillydong/dbdiffer since it supports both MySQL 5 and MySQL 8. This PHP version is too old and I haven't test it in MySQL 8. I'm really not sure about its compatibility. 
If you have any question, you are welcomed to mail me at njutczd@gmail.com directly.

**Comment by JBlond** [comment]
Thank you
